---
- name: Test playbook
  hosts: all
  become: yes
  roles:
    - configure_server

- name: another playbook
  hosts: all

  tasks:

  - name: Test task after roles
    shell:
      cmd: "date"
    register: date_output
  
  - debug:
      msg: "{{ date_output.stdout }}"
